# Generated by Django 4.2.1 on 2023-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('content_summary', models.TextField(blank=True)),
                ('wordcloud', models.ImageField(blank=True, upload_to='wordclouds/')),
            ],
        ),
    ]
