# Generated by Django 4.2.1 on 2023-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document_word_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gpt_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
